iadvize/eslint-configs-library

packages/eslint-config/CHANGELOG.md
packages/eslint-config/light-typescript-react.js
packages/eslint-config/light-typescript.js
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/eslint-config/typescript-react.js
packages/eslint-config/typescript.js

NO-TICKET: add eslint-import-resolver-typescript

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/javascript-react.js
packages/eslint-config/javascript.js
packages/eslint-config/light-typescript-react.js
packages/eslint-config/light-typescript.js
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/eslint-config/patch/index.js
packages/eslint-config/shared/typescript.js
packages/eslint-config/typescript-react.js
packages/eslint-config/typescript.js

Update eslint-config for eslint v7

---

packages/eslint-config-jest/CHANGELOG.md

jest config v1 bump

---

packages/eslint-config/CHANGELOG.md

NO-TICKET: minor bump for eslint-config

---

packages/eslint-config-redux-saga/CHANGELOG.md

NO-TICKET: minor bump for eslint-config-redux-saga

---

packages/eslint-config-jest/CHANGELOG.md

NO-TICKET: minor bump for eslint-config-jest

---

packages/eslint-config-mocha/CHANGELOG.md

NO-TICKET: minor bump for eslint-config-mocha

---

packages/eslint-config-storybook/CHANGELOG.md

NO-TICKET: minor bump for eslint-config-storybook

---

packages/eslint-config-mocha/CHANGELOG.md
packages/eslint-config-mocha/package.json

NO-TICKET: allow eslint v7 in eslint-config-mocha

---

packages/eslint-config-storybook/CHANGELOG.md
packages/eslint-config-storybook/package.json

NO-TICKET: allow eslint v7 for eslint-config-storybook

---

packages/eslint-config-redux-saga/CHANGELOG.md
packages/eslint-config-redux-saga/package.json

NO-TICKET: allow eslint v7 in eslint-config-redux-saga

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/light-typescript-react.js
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/eslint-config/shared/typescript.js

NO-TICKET: fix eslint-config typescript parser

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/light-typescript-react.js
packages/eslint-config/shared/typescript-react.js
packages/eslint-config/typescript-react.js

NO-TICKET: fix typescript-react react rules override

---

packages/eslint-config/CHANGELOG.md

NO-TICKET: fix eslint patch

---

packages/eslint-config-mocha/CHANGELOG.md
packages/eslint-config-mocha/index.js
packages/eslint-config-mocha/package-lock.json
packages/eslint-config-mocha/package.json

NO-TICKET: no need for patch in eslint-config-mocha

---

packages/eslint-config-redux-saga/CHANGELOG.md
packages/eslint-config-redux-saga/index.js
packages/eslint-config-redux-saga/package-lock.json
packages/eslint-config-redux-saga/package.json

NO-TICKET: no need for patch in redux-saga

---

packages/eslint-config-storybook/CHANGELOG.md
packages/eslint-config-storybook/index.js
packages/eslint-config-storybook/package-lock.json
packages/eslint-config-storybook/package.json

NO-TICKET: remove patch from eslint-config-storybook

---

packages/eslint-config/CHANGELOG.md

This PR will create a new release to use the bumped dependencies via dependabot

NO-TICKET: bump dependencies

---

.github/workflows/canary.yml
.github/workflows/ci.yml
.github/workflows/dependabot-pull.yml
.github/workflows/deployment.yml
.github/workflows/merge.yml
.github/workflows/on-merge.yml
.github/workflows/pull-assignee.yml
.github/workflows/pull-changelog.yml
.github/workflows/pull-create-labels-from-files.yml
.github/workflows/pull-labels.yml
.github/workflows/rebase.yml
packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json

What this PR does / why we need it:
Which issue(s) this PR fixes:
- Fixes #

NO-TICKET: Update eslint version

---

packages/eslint-config-redux-saga/CHANGELOG.md
packages/eslint-config-redux-saga/package-lock.json
packages/eslint-config-redux-saga/package.json

What this PR does / why we need it:
Which issue(s) this PR fixes:
- Fixes #

Update deps for esling-config-redux-saga
